.TH intersect 1 "4 AUG 2017" "1.0" "intersect man page"

.SH NAME
intersect - find common words

.SH SYNOPSIS
.B intersect 
...
.B [
.I FILES
.B ]

.SH DESCRIPTION
This manual documents the
.B intersect
tool.
.B intersect
finds all words common between files and prints in alphabetic order.

.SH AUTHOR
Written by Josh Abraham.

.SH REPORTING BUGS
Help at https://github.com/jabedude/

.SH COPYRIGHT
Copyright (c) 2017 Joshua Abraham MIT License
